### ISSUE TITLE
The name of cmp() seems misleading

### ISSUE THREAD

**Issue by heyx3** [VinGarcia/Simple-Iterator-Template#12]
Am I just unfamiliar with C++, or is it very counter-intuitive for `bool cmp()` to be expected to return true if the two iterators are _not_ equal? Normally if I see a function named "compare" that returns a boolean, I'd assume it's an equality check, not a non-equality check.

I spent a while trying to find a bug with my iterator, only to eventually discover that this was the source of it :P

**Comment by VinGarcia** [comment]
Oh, I see, actually, it's been some time since I last implemented this. I probably had a good reason for this, but I don't remember xP.

**Comment by VinGarcia** [comment]
But I am pretty sure I was following a convention

**Comment by heyx3** [comment]
Up to you whether to change it, but if you leave it as is, at least consider a clear note about it somewhere that can't be missed

**Comment by VinGarcia** [comment]
@heyx3 I've created a PR for that too:

https://github.com/VinGarcia/Simple-Iterator-Template/pull/14

If you think it is good I will merge it, (yeah I know I am breaking backward compatibility this time 😅, but I actually care a lot about semantics and readability hehe)

**Comment by VinGarcia** [comment]
Renamed and merged, I also added a Change Log section to the README file in case this breaks someone's code.

Thanks for the feedbacks @heyx3
