### ISSUE TITLE
BUG?operator++()?

### ISSUE THREAD

**Issue by boost2017** [VinGarcia/Simple-Iterator-Template#4]
I am not sure if this is a bug.
post ++ and pre ++ should be different. One return the itertor before increase, and the other return the itertor after increase.
Looks like the code for `operator++()` and `operator++(int)`  return the same iterator.

possible fix

```
		iterator& operator++() { next(); return *this; }
		iterator operator++(int) { iterator temp(*this); next(); return temp; }

```

**Comment by VinGarcia** [comment]
Yes, it is a bug, never thought about it before hehe.

I'll read your PR and merge it as soon as I can. Thank you =]

**Comment by VinGarcia** [comment]
Very clean fix, thank you =]. Just merged your changes.
