### ISSUE TITLE
type first seen using 'struct' now seen using 'class'

### ISSUE THREAD

**Issue by aegonzalez** [VinGarcia/Simple-Iterator-Template#7]
Hi,
Compilation using VS2017 results in the following warning:
iterator_tpl.h(282): warning C4099: 'iterator_tpl::iterator<C,T,S>': type name first seen using 'struct' now seen using 'class'
iterator_tpl.h(291): note: see reference to class template instantiation 'iterator_tpl::const_iterator<C,T,S>' being compiled
--
I changed line 282:
 friend class iterator_tpl::iterator<C,T,S>;
to:
 friend struct iterator_tpl::iterator<C,T,S>;
----
That eliminated the warning.

**Comment by VinGarcia** [comment]
Hello @aegonzalez, thanks for reporting this problem, I have made the changes you have recommended =].

However, I don't currently have an environment with VS2017 installed. Would it be possible for you to test the latest version of the library to check if the warning is really gone? If it is we can close the issue.

**Comment by aegonzalez** [comment]
Sure thing.
I replaced my copy with the latest version. It compiled with no errors or warnings. 
Thanks for fast response.
Looking forward to using your iterator class.
